# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  deliverToClientRepositry:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: git checkout test
      - run: git merge  master
      - run: git push origin test
workflows:
  build-and-deploy:
    jobs:
      - deliverToClientRepositry:
          filters:
            branches:
              only: master
